In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [59]:
df = pd.read_excel("data/data.xlsx")
df

      Latitude  Longitude
0    28.554059  77.224197
1    28.520706  77.123942
2    28.509470  77.129239
3    28.448789  77.165972
4    28.469226  77.156360
5    28.453974  77.148733
6    28.436414  77.152414
7    28.470703  77.198235
8    28.514746  77.199389
9    28.479806  77.238213
10   28.457628  77.196370
11   28.534882  77.240125
12   28.547679  77.141072
13   28.429082  77.220591
14   28.468457  77.187468
15   28.545159  77.235588
16   28.505834  77.189284
17   28.466613  77.243473
18   28.427089  77.237097
19   28.554070  77.250280
20   28.450273  77.202185
21   28.420872  77.257839
22   28.547220  77.123915
23   28.471132  77.239355
24   28.467301  77.220702
25   28.462172  77.144650
26   28.546492  77.160224
27   28.456704  77.180097
28   28.508013  77.158120
29   28.464154  77.190155
..         ...        ...
870  28.824007  77.134356
871  28.753623  77.165813
872  28.723743  77.038773
873  28.850106  77.118895
874  28.806357  77.069637
875  28.752982  77.114278
876  28.757214  76.994545
877  28.737202  77.057634
878  28.783826  77.212382
879  28.805538  77.168567
880  28.732571  77.004192
881  28.764805  77.093972
882  28.857534  77.197153
883  28.855597  77.054410
884  28.745341  77.165318
885  28.790140  77.036879
886  28.798754  77.070211
887  28.839006  77.134500
888  28.750131  77.195422
889  28.723686  77.007163
890  28.836104  77.076666
891  28.794889  76.985619
892  28.821263  77.168578
893  28.806317  77.082080
894  28.858060  77.044839
895  28.797338  77.007542
896  28.777932  77.147253
897  28.800611  77.092581
898  28.756250  77.136922
899  28.837811  77.180344

[900 rows x 2 columns]

In [60]:
df['class'] = ''
for i in range(1,41):
    val = np.random.choice(df.index.values, replace=False)
    df['class'][val] = 1

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [70]:
for i in range(1,7):
    val = np.random.choice(df[df['class'] == ''].index.values, replace=False)
    df['class'][val] = 6
len(df[df['class'] == ''].index.values)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

0

In [72]:
df

      Latitude  Longitude class
0    28.554059  77.224197     3
1    28.520706  77.123942     5
2    28.509470  77.129239     6
3    28.448789  77.165972     3
4    28.469226  77.156360     3
5    28.453974  77.148733     3
6    28.436414  77.152414     4
7    28.470703  77.198235     3
8    28.514746  77.199389     4
9    28.479806  77.238213     4
10   28.457628  77.196370     3
11   28.534882  77.240125     4
12   28.547679  77.141072     5
13   28.429082  77.220591     2
14   28.468457  77.187468     5
15   28.545159  77.235588     4
16   28.505834  77.189284     3
17   28.466613  77.243473     3
18   28.427089  77.237097     4
19   28.554070  77.250280     5
20   28.450273  77.202185     2
21   28.420872  77.257839     4
22   28.547220  77.123915     5
23   28.471132  77.239355     4
24   28.467301  77.220702     3
25   28.462172  77.144650     2
26   28.546492  77.160224     5
27   28.456704  77.180097     3
28   28.508013  77.158120     4
29   28.464154  77.190155     4
..         ...        ...   ...
870  28.824007  77.134356     3
871  28.753623  77.165813     3
872  28.723743  77.038773     2
873  28.850106  77.118895     3
874  28.806357  77.069637     4
875  28.752982  77.114278     1
876  28.757214  76.994545     5
877  28.737202  77.057634     3
878  28.783826  77.212382     3
879  28.805538  77.168567     3
880  28.732571  77.004192     3
881  28.764805  77.093972     3
882  28.857534  77.197153     5
883  28.855597  77.054410     3
884  28.745341  77.165318     4
885  28.790140  77.036879     3
886  28.798754  77.070211     4
887  28.839006  77.134500     3
888  28.750131  77.195422     3
889  28.723686  77.007163     1
890  28.836104  77.076666     3
891  28.794889  76.985619     2
892  28.821263  77.168578     5
893  28.806317  77.082080     2
894  28.858060  77.044839     2
895  28.797338  77.007542     3
896  28.777932  77.147253     3
897  28.800611  77.092581     2
898  28.756250  77.136922     5
899  28.837811  77.180344     4

[900 rows x 3 columns]

In [74]:
df.to_csv('location_dataset', index=False)